"""
DAI Decision Record Schema
===========================

Pydantic v2 models for the Decision Authority Infrastructure ledger.

EU AI Act Article 19 relevance:
    Article 19 of the EU AI Act requires providers of high-risk AI systems to
    keep logs of the system's operation to enable post-hoc monitoring. DAI's
    DecisionRecord schema captures every field required by Article 19:

    - Agent identity and authority (agent_id, agent_type, authorized_scope)
    - Policy traceability (policy_id, policy_version, clauses_applied)
    - Decision outcome and confidence (outcome, confidence)
    - Human oversight status (human_oversight_required, override_applied)
    - Exception handling (exception_applied, exception_type)
    - Cryptographic integrity (record_hash, previous_hash — hash chain)
    - Timestamping with microsecond precision (decision_timestamp, commit_timestamp)

Every DecisionRecord is immutable (frozen=True) after creation and linked
to the previous record via SHA-256 hash chaining.
"""

import json
import re
from datetime import datetime
from enum import StrEnum
from typing import Any, Self

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

# ─── Constants ────────────────────────────────────────────────────────────────

GENESIS_HASH: str = "0" * 64
LEDGER_VERSION: str = "0.1.0"

# PEP 695 type aliases (Python 3.12+)
type SemVerStr = str
type HexHashStr = str

SEMVER_RE: re.Pattern[str] = re.compile(r"^\d+\.\d+\.\d+$")
HEX64_RE: re.Pattern[str] = re.compile(r"^[0-9a-f]{64}$")


# ─── Enums ────────────────────────────────────────────────────────────────────


class AgentType(StrEnum):
    """Classification of the AI agent's level of autonomy."""

    autonomous = "autonomous"
    """Agent acts without human review on individual decisions."""

    human_assisted = "human_assisted"
    """Agent makes recommendations; human approves high-risk cases."""

    human_in_loop = "human_in_loop"
    """Human approves every decision before it is enacted."""


class ContextCompleteness(StrEnum):
    """Indicates whether the agent had all context it needed to decide."""

    full = "full"
    """All expected data sources and evidence were available."""

    partial = "partial"
    """Some expected data was missing but decision was still made."""

    degraded = "degraded"
    """Significant context was missing; decision made under uncertainty."""


class ExceptionType(StrEnum):
    """Classification of why a decision deviated from the standard path."""

    conservative_fallback = "conservative_fallback"
    """Agent fell back to a safe default due to insufficient confidence."""

    manual_override = "manual_override"
    """A human explicitly overrode the agent's decision."""

    policy_exception = "policy_exception"
    """A named policy exception was applied (e.g. whitelist, exemption)."""

    threshold_breach = "threshold_breach"
    """A metric threshold was breached, triggering exception handling."""


class DecisionOutcome(StrEnum):
    """Base outcome enum. Domain-specific outcomes extend via metadata."""

    approved = "approved"
    denied = "denied"
    escalated = "escalated"
    flagged = "flagged"
    deferred = "deferred"


class LedgerVersion(StrEnum):
    """Current ledger schema version."""

    v0_1_0 = "0.1.0"


# ─── Core Decision Record ─────────────────────────────────────────────────────


class DecisionRecord(BaseModel):
    """
    A single immutable decision record in the DAI ledger.

    This is the canonical record written to the append-only ledger. It is
    frozen after creation — no field may be mutated. Records are linked via
    SHA-256 hash chaining for tamper evidence.

    Field descriptions follow EU AI Act Article 19 logging requirements.
    """

    model_config = ConfigDict(
        frozen=True,
        populate_by_name=True,
        json_encoders={
            datetime: lambda v: v.strftime("%Y-%m-%dT%H:%M:%S.%f") + "Z",
        },
    )

    # ── Identity & Integrity ──────────────────────────────────────────────────

    decision_id: str = Field(
        description=(
            "UUIDv7 identifier for this decision record. "
            "Generated by the SDK using uuid6. Globally unique."
        )
    )

    record_hash: HexHashStr = Field(
        description=(
            "SHA-256 hash of (previous_hash + ':' + canonical_json(this record)). "
            "64-character lowercase hex string. Computed by the hash chain engine."
        )
    )

    previous_hash: HexHashStr = Field(
        description=(
            "record_hash of the immediately preceding record in the ledger. "
            "GENESIS_HASH ('0' * 64) for the first record ever committed."
        )
    )

    ledger_version: SemVerStr = Field(
        default=LEDGER_VERSION,
        description="Semver version of the DAI ledger schema. Currently '0.1.0'.",
    )

    # ── Timestamps ────────────────────────────────────────────────────────────

    decision_timestamp: datetime = Field(
        description=(
            "UTC datetime (microsecond precision) when the agent made this decision. "
            "Must be timezone-aware. Set by the SDK at commit time."
        )
    )

    policy_snapshot_at: datetime = Field(
        description=(
            "UTC datetime when the policy version referenced by this record "
            "was resolved/loaded by the agent. Enables policy drift detection."
        )
    )

    commit_timestamp: datetime = Field(
        description=(
            "UTC datetime when this record was accepted by the DAI server. "
            "Set server-side on ingest, not by the SDK client."
        )
    )

    # ── Agent Identity ────────────────────────────────────────────────────────

    agent_id: str = Field(
        description=(
            "Unique identifier of the agent that made this decision. "
            "Examples: 'claims-agent-01', 'fraud-detector-v2'."
        )
    )

    agent_type: AgentType = Field(
        description="Level of human oversight for this agent's decisions."
    )

    model_version: str = Field(
        description=(
            "Exact model identifier used by the agent. "
            "Examples: 'gpt-4o-2024-08-06', 'claude-3-5-sonnet-20241022', 'custom-v1'."
        )
    )

    deployment_id: str | None = Field(
        default=None,
        description=(
            "Optional deployment/environment identifier. "
            "Useful for distinguishing prod vs staging agents."
        ),
    )

    # ── Authority & Scope ─────────────────────────────────────────────────────

    authorized_scope: str = Field(
        description=(
            "Description of what this agent was permitted to decide. "
            "Example: 'motor claims triage up to £10,000'."
        )
    )

    delegation_source: str = Field(
        description=(
            "Who or what granted this agent its decision-making authority. "
            "Example: 'underwriting-team', 'policy:auto-approval-rules-v3'."
        )
    )

    human_oversight_required: bool = Field(
        description=(
            "Whether this decision type requires human review before enactment. "
            "True triggers an oversight workflow in compliant systems."
        )
    )

    # ── Override Tracking ─────────────────────────────────────────────────────

    override_applied: bool = Field(
        description="True if a human explicitly overrode the agent's decision."
    )

    override_by: str | None = Field(
        default=None,
        description=(
            "Role or identifier of the human who applied the override. "
            "Required if override_applied=True. Example: 'senior-underwriter:jane.smith'."
        ),
    )

    override_justification: ExceptionType | None = Field(
        default=None,
        description="Classification of why the override was applied.",
    )

    # ── Decision Content ──────────────────────────────────────────────────────

    decision_type: str = Field(
        description=(
            "Domain-specific classification of the decision. "
            "Examples: 'claims_triage', 'risk_classification', 'fraud_screening'."
        )
    )

    subject_ref: str = Field(
        description=(
            "Opaque reference to the subject of this decision. "
            "Examples: 'claim:ABC123', 'customer:98765', 'application:XYZ'."
        )
    )

    policy_id: str = Field(
        description="Identifier of the policy document governing this decision."
    )

    policy_version: SemVerStr = Field(
        description="Semver version of the policy at decision time. Example: '3.2.1'."
    )

    clauses_applied: list[str] = Field(
        default_factory=list,
        description="List of specific policy clause IDs that governed this decision.",
    )

    # ── Outcome ───────────────────────────────────────────────────────────────

    outcome: str = Field(
        description=(
            "The decision outcome. Domain-specific string, validated against "
            "allowed_outcomes for the decision_type. "
            "Base values: approved, denied, escalated, flagged, deferred."
        )
    )

    confidence: float = Field(
        ge=0.0,
        le=1.0,
        description="Agent confidence in this outcome, 0.0 (none) to 1.0 (certain).",
    )

    alternatives_considered: int | None = Field(
        default=None,
        description="Number of alternative outcomes the agent evaluated before deciding.",
    )

    # ── Evidence & Context ────────────────────────────────────────────────────

    evidence_refs: list[str] = Field(
        description=(
            "References to documents, data points, or signals that informed this decision. "
            "At least one required. Examples: ['claim-form:v3', 'photo:damage-01']."
        )
    )

    data_sources_accessed: list[str] = Field(
        description=(
            "Names of data systems queried to make this decision. "
            "At least one required. Examples: ['claims-db', 'fraud-api', 'policy-db']."
        )
    )

    context_completeness: ContextCompleteness = Field(
        description="Whether the agent had all context it needed to decide reliably."
    )

    # ── Exception Handling ────────────────────────────────────────────────────

    exception_applied: bool = Field(
        description="True if a non-standard exception path was applied in this decision."
    )

    exception_type: ExceptionType | None = Field(
        default=None,
        description="Classification of the exception. Required if exception_applied=True.",
    )

    exception_reason_code: str | None = Field(
        default=None,
        description=(
            "Domain-specific reason code for the exception, validated against "
            "the allowed codes for this decision_type."
        ),
    )

    # ── Extension ─────────────────────────────────────────────────────────────

    metadata: dict[str, str] = Field(
        default_factory=dict,
        description=(
            "Extension point for domain-specific metadata. "
            "All values must be strings. Keys and values are stored as-is."
        ),
    )

    # ── Validators ────────────────────────────────────────────────────────────

    @field_validator("record_hash", "previous_hash")
    @classmethod
    def validate_hex64(cls, v: str, info: Any) -> str:
        if not HEX64_RE.match(v):
            raise ValueError(
                f"{info.field_name} must be a 64-character lowercase hex string, got: {v!r}"
            )
        return v

    @field_validator("policy_version", "ledger_version")
    @classmethod
    def validate_semver(cls, v: str, info: Any) -> str:
        if not SEMVER_RE.match(v):
            raise ValueError(
                f"{info.field_name} must match semver pattern X.Y.Z, got: {v!r}"
            )
        return v

    @field_validator("ledger_version")
    @classmethod
    def validate_ledger_version(cls, v: str) -> str:
        if v != LEDGER_VERSION:
            raise ValueError(
                f"ledger_version must be '{LEDGER_VERSION}', got: {v!r}"
            )
        return v

    @field_validator("decision_timestamp", "policy_snapshot_at", "commit_timestamp")
    @classmethod
    def validate_utc_aware(cls, v: datetime, info: Any) -> datetime:
        if v.tzinfo is None:
            raise ValueError(f"{info.field_name} must be timezone-aware (UTC)")
        return v

    @field_validator("evidence_refs")
    @classmethod
    def validate_evidence_refs(cls, v: list[str]) -> list[str]:
        if len(v) < 1:
            raise ValueError("evidence_refs must contain at least 1 item")
        return v

    @field_validator("data_sources_accessed")
    @classmethod
    def validate_data_sources(cls, v: list[str]) -> list[str]:
        if len(v) < 1:
            raise ValueError("data_sources_accessed must contain at least 1 item")
        return v

    @field_validator("metadata")
    @classmethod
    def validate_metadata_string_values(cls, v: dict[str, str]) -> dict[str, str]:
        for key, value in v.items():
            if not isinstance(value, str):
                raise ValueError(
                    f"metadata values must all be strings; got {type(value).__name__} for key {key!r}"
                )
        return v

    @model_validator(mode="after")
    def validate_override_consistency(self) -> Self:
        if self.override_applied and self.override_by is None:
            raise ValueError(
                "override_by must be set when override_applied=True"
            )
        return self

    @model_validator(mode="after")
    def validate_exception_consistency(self) -> Self:
        if self.exception_applied and self.exception_type is None:
            raise ValueError(
                "exception_type must be set when exception_applied=True"
            )
        return self

    # ── Methods ───────────────────────────────────────────────────────────────

    def to_canonical_json(self) -> str:
        """
        Produce a deterministic JSON string of this record for hashing.

        The record_hash field itself is excluded so that the hash can be
        computed before it is known. Keys are sorted for determinism.

        Determinism guarantees:
        - Keys are sorted alphabetically (sort_keys equivalent)
        - Datetimes serialised as ISO8601 with Z suffix
        - Floats use Python's standard repr (no locale formatting)
        - No trailing whitespace or variable indentation
        """
        data = self.model_dump(exclude={"record_hash"}, mode="json")
        return json.dumps(data, sort_keys=True, separators=(",", ":"), default=str)

    def to_audit_dict(self) -> dict[str, Any]:
        """
        Return a human-readable dict suitable for export, logging, and reports.

        All datetime fields are rendered as ISO8601 strings.
        Enum fields are rendered as their string values.
        """
        return self.model_dump(mode="json")


# ─── Create Request (caller-facing) ───────────────────────────────────────────


class DecisionRecordCreate(BaseModel):
    """
    Input model for creating a new decision record.

    This is what callers provide. The SDK fills in:
    - decision_id (UUIDv7)
    - record_hash (computed by hash chain engine)
    - previous_hash (fetched from ledger)
    - commit_timestamp (set server-side)
    - ledger_version (set by SDK constant)
    """

    model_config = ConfigDict(populate_by_name=True)

    # Required fields
    agent_id: str
    agent_type: AgentType = AgentType.autonomous
    model_version: str = "unknown"
    deployment_id: str | None = None
    authorized_scope: str
    delegation_source: str
    human_oversight_required: bool = False
    override_applied: bool = False
    override_by: str | None = None
    override_justification: ExceptionType | None = None
    decision_type: str
    subject_ref: str
    policy_id: str
    policy_version: str
    policy_snapshot_at: datetime
    clauses_applied: list[str] = Field(default_factory=list)
    outcome: str
    confidence: float = Field(ge=0.0, le=1.0)
    alternatives_considered: int | None = None
    evidence_refs: list[str]
    data_sources_accessed: list[str]
    context_completeness: ContextCompleteness = ContextCompleteness.full
    exception_applied: bool = False
    exception_type: ExceptionType | None = None
    exception_reason_code: str | None = None
    metadata: dict[str, str] = Field(default_factory=dict)

    # Optional: caller may provide decision_timestamp; SDK sets it if not given
    decision_timestamp: datetime | None = None

    @field_validator("policy_version")
    @classmethod
    def validate_semver(cls, v: str) -> str:
        if not SEMVER_RE.match(v):
            raise ValueError(f"policy_version must match semver X.Y.Z, got: {v!r}")
        return v

    @model_validator(mode="after")
    def validate_override_consistency(self) -> Self:
        if self.override_applied and self.override_by is None:
            raise ValueError("override_by must be set when override_applied=True")
        return self

    @model_validator(mode="after")
    def validate_exception_consistency(self) -> Self:
        if self.exception_applied and self.exception_type is None:
            raise ValueError("exception_type must be set when exception_applied=True")
        return self


# ─── Chain Verification Result ────────────────────────────────────────────────


class ChainVerifyResult(BaseModel):
    """Result of verifying the integrity of a hash chain."""

    valid: bool = Field(description="True if the entire chain is intact and untampered.")
    total_records: int = Field(description="Number of records verified.")
    broken_at: str | None = Field(
        default=None,
        description="decision_id of the first record where the chain breaks, if any.",
    )
    verified_at: datetime = Field(description="UTC datetime when verification ran.")
    message: str = Field(description="Human-readable summary of the verification result.")


# ─── Query Filter ──────────────────────────────────────────────────────────────


class QueryFilter(BaseModel):
    """Filter parameters for querying decision records."""

    model_config = ConfigDict(populate_by_name=True)

    decision_id: str | None = None
    agent_id: str | None = None
    decision_type: str | None = None
    from_timestamp: datetime | None = None
    to_timestamp: datetime | None = None
    outcome: str | None = None
    exception_applied: bool | None = None
    override_applied: bool | None = None
    limit: int = Field(default=100, ge=1, le=1000)
    cursor: str | None = Field(
        default=None,
        description="decision_id to use as cursor for keyset pagination.",
    )


# ─── Article 19 Export Request ────────────────────────────────────────────────


class Article19ExportRequest(BaseModel):
    """Request parameters for generating an EU AI Act Article 19 compliance export."""

    from_timestamp: datetime = Field(description="Start of the reporting period (UTC).")
    to_timestamp: datetime = Field(description="End of the reporting period (UTC).")
    agent_ids: list[str] | None = Field(
        default=None,
        description="Filter export to specific agent IDs. None means all agents.",
    )
    decision_types: list[str] | None = Field(
        default=None,
        description="Filter export to specific decision types. None means all types.",
    )
    include_chain_proof: bool = Field(
        default=True,
        description="Whether to include hash chain verification in the export.",
    )
